// This file is auto-generated by manage-i18n.js
// Do not edit this file directly

export interface MessageSchema {
  navbar: {
    aiConfig: string;
    apiConnections: string;
    formatting: string;
    worldInfo: string;
    userSettings: string;
    backgrounds: string;
    extensions: string;
    personaManagement: string;
    characterManagement: string;
    recentChats: string;
  };
  formatting: {
    title: string;
    description: string;
  };
  chatManagement: {
    newChat: string;
    createPrompt: string;
    renamePrompt: string;
    deleteConfirmTitle: string;
    deleteConfirmContent: string;
    noRecentChats: string;
    noChatsFound: string;
    scenarioOverride: string;
    scenarioOverridePlaceholder: string;
    deleteSelectedConfirmContent: string;
    deleteSuccess: string;
    actions: {
      rename: string;
      delete: string;
    };
    errors: {
      create: string;
      rename: string;
      delete: string;
    };
    tabs: {
      chats: string;
      group: string;
      prompts: string;
    };
  };
  group: {
    peek: string;
    forceTalk: string;
    mute: string;
    addMember: string;
    replyStrategy: string;
    strategies: {
      manual: string;
      natural: string;
      list: string;
      pooled: string;
    };
    handlingMode: string;
    modes: {
      swap: string;
      joinExclude: string;
      joinInclude: string;
    };
    allowSelfResponses: string;
    autoMode: string;
    autoModeHint: string;
  };
  personaManagement: {
    title: string;
    usageStats: string;
    backup: string;
    restore: string;
    create: string;
    noDescription: string;
    currentPersona: string;
    description: {
      label: string;
      placeholder: string;
    };
    connections: {
      title: string;
      default: string;
      character: string;
      chat: string;
    };
    globalSettings: {
      title: string;
      showNotifications: string;
      allowMultiConnections: string;
      autoLock: string;
    };
    actions: {
      rename: string;
      syncName: string;
      lore: string;
      changeImage: string;
      duplicate: string;
      delete: string;
    };
    rename: {
      title: string;
      prompt: string;
    };
    delete: {
      confirmTitle: string;
      confirmMessage: string;
      success: string;
      error: string;
    };
  };
  worldInfo: {
    activeWorlds: string;
    activeWorldsHint: string;
    globalSettings: string;
    activationSettings: string;
    advancedSettings: string;
    scanDepth: string;
    contextPercent: string;
    budgetCap: string;
    budgetCapHint: string;
    insertionStrategy: string;
    insertionStrategyHint: string;
    insertionStrategies: {
      sortedEvenly: string;
      characterLoreFirst: string;
      globalLoreFirst: string;
    };
    includeNames: string;
    includeNamesHint: string;
    recursiveScan: string;
    recursiveScanHint: string;
    caseSensitive: string;
    caseSensitiveHint: string;
    matchWholeWords: string;
    matchWholeWordsHint: string;
    useGroupScoring: string;
    useGroupScoringHint: string;
    alertOnOverflow: string;
    alertOnOverflowHint: string;
    newWorld: string;
    import: string;
    export: string;
    rename: string;
    duplicate: string;
    newEntryInBook: string;
    deleteBook: string;
    refresh: string;
    searchPlaceholder: string;
    selectEntryPlaceholderTitle: string;
    selectEntryPlaceholderText: string;
    sorting: {
      title: string;
      titleAsc: string;
      titleDesc: string;
      orderAsc: string;
      uidAsc: string;
      uidDesc: string;
    };
    entry: {
      toggle: string;
      titlePlaceholder: string;
      primaryKeywords: string;
      keywordsPlaceholder: string;
      logic: string;
      logicOptions: {
        andAny: string;
        andAll: string;
        notAll: string;
        notAny: string;
      };
      optionalFilter: string;
      filterPlaceholder: string;
      content: string;
      contentPlaceholder: string;
      positionTooltip: string;
      positionOptions: {
        beforeChar: string;
        afterChar: string;
        beforeEM: string;
        afterEM: string;
        beforeAN: string;
        afterAN: string;
        atDepthSystem: string;
        outlet: string;
      };
      depth: string;
      order: string;
      trigger: string;
      move: string;
      duplicate: string;
      delete: string;
      additionalSources: string;
      charDescription: string;
      charPersonality: string;
      scenario: string;
      personaDescription: string;
      charNote: string;
      creatorNotes: string;
      entryState: string;
      entryStates: {
        constant: string;
        normal: string;
        vectorized: string;
      };
    };
    popup: {
      newBookTitle: string;
      newBookContent: string;
      newBookInput: string;
      deleteBookContent: string;
      renameBookTitle: string;
      duplicateBookTitle: string;
      duplicateBookInputSuffix: string;
      deleteEntryTitle: string;
      deleteEntryContent: string;
    };
  };
  backgrounds: {
    add: string;
    fitting: string;
    fittingOptions: {
      classic: string;
      cover: string;
      contain: string;
      stretch: string;
      center: string;
    };
    autoSelect: string;
    autoSelectTooltip: string;
    searchPlaceholder: string;
    systemBackgrounds: string;
    zoomIn: string;
    zoomOut: string;
    confirmDelete: string;
    renameTitle: string;
    renameSuccess: string;
    deleteSuccess: string;
    actions: {
      lock: string;
      unlock: string;
      rename: string;
      delete: string;
    };
    errors: {
      fetch: string;
      noChatLock: string;
      upload: string;
      delete: string;
      rename: string;
    };
  };
  aiConfig: {
    tabSampler: string;
    tabPrompts: string;
    manualInputNote: string;
    docsLinkTooltip: string;
    presets: {
      chatCompletion: {
        label: string;
      };
      import: string;
      export: string;
      delete: string;
      update: string;
      rename: string;
      saveAs: string;
      newName: string;
      renamePopupTitle: string;
      deletePopupContent: string;
      errors: {
        renameDefault: string;
        deleteDefault: string;
        noExportSelected: string;
        exportNotFound: string;
        importInvalid: string;
        noPresetName: string;
      };
    };
    promptManager: {
      label: string;
      description: string;
      noPrompts: string;
      newPrompt: string;
      role: string;
      content: string;
      markerHint: string;
      cannotDeleteMarker: string;
    };
    contextSize: {
      label: string;
      unlocked: string;
      unlockedTooltip: string;
    };
    maxResponseLength: {
      label: string;
    };
    streaming: {
      label: string;
      description: string;
    };
    showThoughts: {
      label: string;
      description: string;
    };
    reasoningEffort: {
      label: string;
      tooltip: string;
      options: {
        auto: string;
        minimum: string;
        low: string;
        medium: string;
        high: string;
        maximum: string;
      };
      descriptionOpenAI: string;
      descriptionClaude: string;
      descriptionGoogle: string;
    };
    temperature: {
      label: string;
    };
    freqPenalty: {
      label: string;
    };
    presPenalty: {
      label: string;
    };
    repPenalty: {
      label: string;
    };
    topK: {
      label: string;
    };
    topP: {
      label: string;
    };
    minP: {
      label: string;
    };
    topA: {
      label: string;
    };
    claude: {
      useSysPrompt: {
        label: string;
        description: string;
      };
      assistantPrefill: {
        label: string;
        description: string;
      };
    };
    google: {
      useSysPrompt: {
        label: string;
        description: string;
      };
    };
  };
  userSettings: {
    title: string;
    searchPlaceholder: string;
    noResults: string;
  };
  api: {
    connectSuccess: string;
    connectFailed: string;
    status: {
      bypassed: string;
      valid: string;
      noConnection: string;
      notConnected: string;
      connecting: string;
      notImplemented: string;
    };
  };
  errors: {
    csrfToken: string;
  };
  common: {
    ok: string;
    cancel: string;
    save: string;
    yes: string;
    no: string;
    loading: string;
    tokens: string;
    confirm: string;
    delete: string;
    of: string;
    search: string;
    resetToDefaults: string;
    confirmDelete: string;
    by: string;
    reset: string;
    copied: string;
    seconds: string;
    remove: string;
    dragToReorder: string;
    toggle: string;
    refresh: string;
    messages: string;
    noResults: string;
    name: string;
    select: string;
    selected: string;
    selectAll: string;
    chat: string;
    new: string;
  };
  popup: {
    cropAvatar: {
      title: string;
    };
  };
  pagination: {
    first: string;
    previous: string;
    next: string;
    last: string;
    perPage: string;
  };
  chat: {
    inputPlaceholder: string;
    options: string;
    extensions: string;
    continue: string;
    send: string;
    loadError: string;
    createError: string;
    emptyLog: string;
    generate: {
      noPrompts: string;
      errorFallback: string;
      noModelError: string;
      noPersonaError: string;
      noSpeaker: string;
    };
    buttons: {
      confirmEdit: string;
      copyMessage: string;
      addReasoning: string;
      deleteMessage: string;
      moveUp: string;
      moveDown: string;
      swipeLeft: string;
      swipeRight: string;
      itemization: string;
    };
    delete: {
      confirmTitle: string;
      confirmMessage: string;
      confirmSwipeMessage: string;
      deleteSwipe: string;
      deleteMessage: string;
      lastSwipeError: string;
    };
    copy: {
      success: string;
      error: string;
    };
    optionsMenu: {
      manageChats: string;
      regenerate: string;
      continue: string;
    };
    typingIndicator: string;
    abort: string;
    reasoning: {
      title: string;
    };
    itemization: {
      title: string;
      apiModel: string;
      preset: string;
      tokenizer: string;
      disclaimer: string;
      systemInfo: string;
      description: string;
      personality: string;
      scenario: string;
      examples: string;
      persona: string;
      worldInfo: string;
      chatHistory: string;
      extensions: string;
      bias: string;
      totalTokens: string;
      maxContext: string;
      showRaw: string;
      showWorldInfo: string;
      copy: string;
    };
  };
  character: {
    import: {
      aborted: string;
      abortedMessage: string;
      unsupportedType: string;
      success: string;
      error: string;
      errorMessage: string;
      tagsImported: string;
      tagsImportedMessage: string;
      tagImportAskNotImplemented: string;
      tagImportExistingNotImplemented: string;
    };
    save: {
      error: string;
      noActive: string;
      syncWarning: string;
    };
    fetch: {
      overflowWarning: string;
    };
    create: {
      success: string;
      error: string;
    };
    delete: {
      confirmTitle: string;
      confirmMessage: string;
      deleteChats: string;
      success: string;
      error: string;
    };
    updateImage: {
      error: string;
    };
    tokenWarning: string;
  };
  characterPanel: {
    pinToggle: string;
    createNew: string;
    importFile: string;
    importUrl: string;
    createGroup: string;
    searchToggle: string;
    searchPlaceholder: string;
    sorting: {
      title: string;
      nameAsc: string;
      nameDesc: string;
      newest: string;
      oldest: string;
      favorites: string;
    };
    editor: {
      placeholderTitle: string;
      placeholderText: string;
      placeholderButton: string;
    };
    collapseBrowser: string;
    expandBrowser: string;
  };
  characterEditor: {
    avatar: string;
    favorite: string;
    lore: string;
    chatLore: string;
    personas: string;
    export: string;
    duplicate: string;
    delete: string;
    more: string;
    searchTags: string;
    viewAllTags: string;
    creatorNotes: string;
    toggleStyles: string;
    toggleSpoiler: string;
    noCreatorNotes: string;
    detailsHidden: string;
    description: string;
    firstMessage: string;
    expandEditor: string;
    namePlaceholder: string;
    descriptionPlaceholder: string;
    firstMessagePlaceholder: string;
    openLastChat: string;
    startNewChat: string;
    tokenCounts: {
      title: string;
      total: string;
      permanent: string;
      warningTooltip: string;
    };
    stats: {
      title: string;
    };
    moreOptions: {
      linkWorldInfo: string;
      importCardLore: string;
      characterSettingsOverrides: string;
      convertToPersona: string;
      rename: string;
      linkToSource: string;
      replaceUpdate: string;
      importTags: string;
      setAsWelcomeAssistant: string;
    };
    advanced: {
      promptOverrides: string;
      promptOverridesHint: string;
      promptHint: string;
      mainPrompt: string;
      mainPromptPlaceholder: string;
      postHistoryInstructions: string;
      postHistoryInstructionsPlaceholder: string;
      metadata: string;
      metadataHint: string;
      metadataOptional: string;
      createdBy: string;
      createdByPlaceholder: string;
      characterVersion: string;
      characterVersionPlaceholder: string;
      creatorNotes: string;
      creatorNotesPlaceholder: string;
      tagsToEmbed: string;
      tagsToEmbedPlaceholder: string;
      personality: string;
      personalityPlaceholder: string;
      scenario: string;
      scenarioPlaceholder: string;
      characterNote: string;
      characterNotePlaceholder: string;
      depth: string;
      role: string;
      talkativeness: string;
      talkativenessHint: string;
      talkativenessShy: string;
      talkativenessNormal: string;
      talkativenessChatty: string;
      dialogueExamples: string;
      dialogueExamplesHint: string;
      dialogueExamplesPlaceholder: string;
      editingTitle: string;
      roles: {
        system: string;
        user: string;
        assistant: string;
      };
    };
    validation: {
      nameRequired: string;
    };
  };
  extensions: {
    notifyUpdates: string;
    manage: string;
    install: string;
    managePopupNotImplemented: string;
    installPopupNotImplemented: string;
    placeholder: {
      title: string;
      text: string;
    };
  };
  apiConnections: {
    profile: string;
    profileManagement: {
      create: string;
      rename: string;
      delete: string;
      import: string;
      export: string;
      none: string;
      createPopupTitle: string;
      profileName: string;
      fieldsToInclude: string;
      renamePopupTitle: string;
      deletePopupContent: string;
      errors: {
        noSelection: string;
        deleteNone: string;
        renameNone: string;
        nameExists: string;
      };
    };
    api: string;
    chatCompletion: string;
    textCompletion: string;
    novel: string;
    horde: string;
    kobold: string;
    source: string;
    openaiKey: string;
    claudeKey: string;
    openrouterKey: string;
    mistralaiKey: string;
    groqKey: string;
    customKey: string;
    azureKey: string;
    manageKeys: string;
    keyPrivacy: string;
    openaiModel: string;
    claudeModel: string;
    mistralaiModel: string;
    groqModel: string;
    customModel: string;
    customUrl: string;
    azureBaseUrl: string;
    azureDeploymentName: string;
    azureApiVersion: string;
    azureModel: string;
    connect: string;
    connecting: string;
    sources: {
      openai: string;
      claude: string;
      openrouter: string;
      custom: string;
      ai21: string;
      aimlapi: string;
      azure_openai: string;
      cohere: string;
      deepseek: string;
      electronhub: string;
      fireworks: string;
      groq: string;
      makersuite: string;
      vertexai: string;
      mistralai: string;
      moonshot: string;
      nanogpt: string;
      perplexity: string;
      pollinations: string;
      xai: string;
      zai: string;
    };
    modelGroups: {
      gpt4o: string;
      gpt4turbo: string;
      other: string;
    };
    openrouterModel: string;
    openrouterWebsite: string;
    openrouterOptions: string;
    openrouterUseFallback: string;
    openrouterAllowFallbacks: string;
    openrouterFallbackProviders: string;
    openrouterMiddleout: string;
    middleout: {
      on: string;
      off: string;
      auto: string;
    };
    tokenizer: string;
    tokenizers: {
      auto: string;
      none: string;
      llama: string;
      llama3: string;
      mistral: string;
      yi: string;
      claude: string;
      gemma: string;
      jamba: string;
      qwen2: string;
      commandr: string;
      commanda: string;
      nemo: string;
      deepseek: string;
      gpt2: string;
      gpt35: string;
      gpt4o: string;
    };
  };
  settings: {
    powerUser: {
      spoilerFreeMode: {
        label: string;
        description: string;
      };
      neverResizeAvatars: {
        label: string;
        description: string;
      };
      sendOnEnter: {
        label: string;
        description: string;
        options: {
          disabled: string;
          auto: string;
          enabled: string;
        };
      };
      worldImportDialog: {
        label: string;
        description: string;
      };
      confirmMessageDelete: {
        label: string;
        description: string;
      };
      zoomedAvatarMagnification: {
        label: string;
        description: string;
      };
      tagImportSetting: {
        label: string;
        description: string;
        options: {
          none: string;
          all: string;
          only_existing: string;
          ask: string;
        };
      };
      personaShowNotifications: {
        label: string;
        description: string;
      };
      personaAllowMultiConnections: {
        label: string;
        description: string;
      };
      personaAutoLock: {
        label: string;
        description: string;
      };
    };
    background: {
      thumbnailColumns: {
        label: string;
        description: string;
      };
      animation: {
        label: string;
        description: string;
      };
    };
    ui: {
      chat: {
        reasoningCollapsed: {
          label: string;
          description: string;
        };
      };
    };
  };
  extensionsBuiltin: {
    chatTranslation: {
      connectionProfile: string;
      connectionProfileHint: string;
      sourceLang: string;
      targetLang: string;
      autoMode: {
        label: string;
        none: string;
        responses: string;
        inputs: string;
        both: string;
      };
      promptTemplate: string;
      promptHint: string;
    };
    rerollContinue: {
      buttonLabel: string;
      noSnapshot: string;
      contextChanged: string;
      divergenceError: string;
      swipeError: string;
      reverting: string;
      error: string;
    };
  };
}
