// This file is auto-generated by generate-i18n-types.js
// Do not edit this file directly

export interface MessageSchema {
  sidebar: {
    aiConfig: string;
    apiConnections: string;
    formatting: string;
    worldInfo: string;
    userSettings: string;
    backgrounds: string;
    extensions: string;
    personaManagement: string;
    characterManagement: string;
  };
  personaManagement: {
    title: string;
    usageStats: string;
    backup: string;
    restore: string;
    create: string;
    noDescription: string;
    currentPersona: string;
    description: {
      label: string;
      placeholder: string;
    };
    connections: {
      title: string;
      default: string;
      character: string;
      chat: string;
    };
    globalSettings: {
      title: string;
      showNotifications: string;
      allowMultiConnections: string;
      autoLock: string;
    };
    actions: {
      rename: string;
      syncName: string;
      lore: string;
      changeImage: string;
      duplicate: string;
      delete: string;
    };
    rename: {
      title: string;
      prompt: string;
    };
    delete: {
      confirmTitle: string;
      confirmMessage: string;
      success: string;
      error: string;
    };
  };
  worldInfo: {
    title: string;
    pinToggle: string;
    docsLink: string;
    activeWorlds: string;
    noWorldsActive: string;
    globalSettings: string;
    expand: string;
    scanDepth: string;
    contextPercent: string;
    budgetCap: string;
    budgetCapHint: string;
    minActivations: string;
    minActivationsHint: string;
    minActivationsDisabledHint: string;
    maxDepth: string;
    maxDepthHint: string;
    maxRecursionSteps: string;
    maxRecursionStepsHint: string;
    maxRecursionStepsDisabledHint: string;
    insertionStrategy: string;
    insertionStrategies: {
      sortedEvenly: string;
      characterLoreFirst: string;
      globalLoreFirst: string;
    };
    includeNames: string;
    includeNamesHint: string;
    recursiveScan: string;
    recursiveScanHint: string;
    caseSensitive: string;
    caseSensitiveHint: string;
    matchWholeWords: string;
    matchWholeWordsHint: string;
    useGroupScoring: string;
    useGroupScoringHint: string;
    alertOnOverflow: string;
    alertOnOverflowHint: string;
    newWorld: string;
    or: string;
    pickToEdit: string;
    import: string;
    export: string;
    rename: string;
    duplicate: string;
    delete: string;
    newEntry: string;
    openAllEntries: string;
    closeAllEntries: string;
    fillEmptyMemos: string;
    applySorting: string;
    refresh: string;
    searchPlaceholder: string;
    sorting: {
      search: string;
      priority: string;
      custom: string;
      titleAsc: string;
      titleDesc: string;
      tokensAsc: string;
      tokensDesc: string;
      depthAsc: string;
      depthDesc: string;
      orderAsc: string;
      orderDesc: string;
      uidAsc: string;
      uidDesc: string;
      triggerAsc: string;
      triggerDesc: string;
    };
    entry: {
      toggle: string;
      titlePlaceholder: string;
      primaryKeywords: string;
      keywordsPlaceholder: string;
      logic: string;
      logicOptions: {
        andAny: string;
        andAll: string;
        notAll: string;
        notAny: string;
      };
      optionalFilter: string;
      filterPlaceholder: string;
      content: string;
      contentPlaceholder: string;
      position: string;
      positionTooltip: string;
      positionOptions: {
        beforeChar: string;
        afterChar: string;
        beforeEM: string;
        afterEM: string;
        beforeAN: string;
        afterAN: string;
        atDepthSystem: string;
        atDepthUser: string;
        atDepthAI: string;
        outlet: string;
      };
      depth: string;
      order: string;
      trigger: string;
      move: string;
      duplicate: string;
      delete: string;
      additionalSources: string;
      charDescription: string;
      charPersonality: string;
      scenario: string;
      personaDescription: string;
      charNote: string;
      creatorNotes: string;
      inclusionGroup: string;
      inclusionGroupHint: string;
      inclusionGroupPlaceholder: string;
      prioritize: string;
      prioritizeHint: string;
      groupWeight: string;
      groupWeightHint: string;
      sticky: string;
      stickyUnit: string;
      stickyHint: string;
      nonSticky: string;
      cooldown: string;
      cooldownHint: string;
      noCooldown: string;
      delay: string;
      delayHint: string;
      noDelay: string;
      nonRecursable: string;
      nonRecursableHint: string;
      preventRecursion: string;
      preventRecursionHint: string;
      delayUntilRecursion: string;
      delayUntilRecursionHint: string;
      ignoreBudget: string;
      ignoreBudgetHint: string;
      entryState: string;
      entryStates: {
        constant: string;
        normal: string;
        vectorized: string;
      };
    };
  };
  backgrounds: {
    add: string;
    fitting: string;
    fittingOptions: {
      classic: string;
      cover: string;
      contain: string;
      stretch: string;
      center: string;
    };
    autoSelect: string;
    autoSelectTooltip: string;
    searchPlaceholder: string;
    systemBackgrounds: string;
    chatBackgrounds: string;
    zoomIn: string;
    zoomOut: string;
    confirmDelete: string;
    renameTitle: string;
    renameSuccess: string;
    deleteSuccess: string;
    actions: {
      lock: string;
      unlock: string;
      copy: string;
      rename: string;
      delete: string;
    };
    errors: {
      fetch: string;
      noChatLock: string;
      upload: string;
      delete: string;
      rename: string;
    };
  };
  aiConfig: {
    manualInputNote: string;
    docsLinkTooltip: string;
    presets: {
      chatCompletion: {
        label: string;
      };
      import: string;
      export: string;
      delete: string;
      update: string;
      rename: string;
      saveAs: string;
      newName: string;
    };
    contextSize: {
      label: string;
      unlocked: string;
      unlockedTooltip: string;
    };
    maxResponseLength: {
      label: string;
    };
    streaming: {
      label: string;
      description: string;
    };
    temperature: {
      label: string;
    };
    freqPenalty: {
      label: string;
    };
    presPenalty: {
      label: string;
    };
    topK: {
      label: string;
    };
    topP: {
      label: string;
    };
  };
  userSettings: {
    title: string;
    searchPlaceholder: string;
    noResults: string;
  };
  api: {
    connectSuccess: string;
    connectFailed: string;
    status: {
      bypassed: string;
      valid: string;
      noConnection: string;
      notConnected: string;
      connecting: string;
      notImplemented: string;
    };
  };
  errors: {
    csrfToken: string;
  };
  common: {
    ok: string;
    cancel: string;
    save: string;
    yes: string;
    no: string;
    back: string;
    loading: string;
    tokens: string;
    permanent: string;
    confirm: string;
    copy: string;
    delete: string;
    of: string;
    search: string;
  };
  pagination: {
    first: string;
    previous: string;
    next: string;
    last: string;
    perPage: string;
  };
  chat: {
    inputPlaceholder: string;
    options: string;
    extensions: string;
    continue: string;
    send: string;
    saveError: string;
    loadError: string;
    generate: {
      noPrompts: string;
      errorFallback: string;
    };
    buttons: {
      confirmEdit: string;
      copyMessage: string;
      addReasoning: string;
      deleteMessage: string;
      moveUp: string;
      moveDown: string;
    };
    delete: {
      confirmTitle: string;
      confirmMessage: string;
      confirmSwipeMessage: string;
      deleteSwipe: string;
      deleteMessage: string;
      lastSwipeError: string;
      noSwipesError: string;
    };
    copy: {
      success: string;
      error: string;
    };
  };
  character: {
    import: {
      aborted: string;
      abortedMessage: string;
      unsupportedType: string;
      success: string;
      error: string;
      errorMessage: string;
      tagsImported: string;
      tagsImportedMessage: string;
      tagImportAskNotImplemented: string;
      tagImportExistingNotImplemented: string;
    };
    save: {
      error: string;
      noActive: string;
      syncWarning: string;
    };
    fetch: {
      error: string;
      overflowWarning: string;
    };
    switch: {
      wait: string;
    };
  };
  characterPanel: {
    pinToggle: string;
    selectCharacter: string;
    hotSwaps: string;
    tokenInfo: string;
    totalTokens: string;
    permanentTokens: string;
    aboutTokens: string;
    stats: string;
    togglePanel: string;
    createNew: string;
    importFile: string;
    importUrl: string;
    createGroup: string;
    searchToggle: string;
    searchPlaceholder: string;
    gridView: string;
    bulkEdit: string;
    bulkSelectAll: string;
    bulkDelete: string;
    sorting: {
      title: string;
      search: string;
      nameAsc: string;
      nameDesc: string;
      newest: string;
      oldest: string;
      favorites: string;
      recent: string;
      mostChats: string;
      leastChats: string;
      mostTokens: string;
      leastTokens: string;
      random: string;
    };
  };
  characterEditor: {
    avatar: string;
    back: string;
    favorite: string;
    advancedDefinitions: string;
    lore: string;
    chatLore: string;
    personas: string;
    export: string;
    duplicate: string;
    delete: string;
    more: string;
    searchTags: string;
    viewAllTags: string;
    creatorNotes: string;
    toggleStyles: string;
    toggleSpoiler: string;
    noCreatorNotes: string;
    detailsHidden: string;
    description: string;
    firstMessage: string;
    expandEditor: string;
    descriptionPlaceholder: string;
    firstMessagePlaceholder: string;
    moreOptions: {
      linkWorldInfo: string;
      importCardLore: string;
      characterSettingsOverrides: string;
      convertToPersona: string;
      rename: string;
      linkToSource: string;
      replaceUpdate: string;
      importTags: string;
      setAsWelcomeAssistant: string;
    };
  };
  advancedDefinitions: {
    title: string;
    promptOverrides: string;
    promptOverridesHint: string;
    promptHint: string;
    mainPrompt: string;
    mainPromptPlaceholder: string;
    postHistoryInstructions: string;
    postHistoryInstructionsPlaceholder: string;
    metadata: string;
    metadataHint: string;
    metadataOptional: string;
    createdBy: string;
    createdByPlaceholder: string;
    characterVersion: string;
    characterVersionPlaceholder: string;
    creatorNotes: string;
    creatorNotesPlaceholder: string;
    tagsToEmbed: string;
    tagsToEmbedPlaceholder: string;
    personality: string;
    personalityPlaceholder: string;
    scenario: string;
    scenarioPlaceholder: string;
    characterNote: string;
    characterNotePlaceholder: string;
    depth: string;
    role: string;
    talkativeness: string;
    talkativenessHint: string;
    talkativenessShy: string;
    talkativenessNormal: string;
    talkativenessChatty: string;
    dialogueExamples: string;
    dialogueExamplesHint: string;
    dialogueExamplesPlaceholder: string;
    editingTitle: string;
    roles: {
      system: string;
      user: string;
      assistant: string;
    };
  };
  extensions: {
    title: string;
    notifyUpdates: string;
    manage: string;
    install: string;
    managePopupNotImplemented: string;
    installPopupNotImplemented: string;
  };
  apiConnections: {
    profile: string;
    profileNotImplemented: string;
    api: string;
    chatCompletion: string;
    textCompletion: string;
    novel: string;
    horde: string;
    kobold: string;
    source: string;
    openaiKey: string;
    openaiKeyPlaceholder: string;
    claudeKey: string;
    claudeKeyPlaceholder: string;
    openrouterKey: string;
    openrouterKeyPlaceholder: string;
    manageKeys: string;
    keyPrivacy: string;
    openaiModel: string;
    claudeModel: string;
    connect: string;
    connecting: string;
    sources: {
      openai: string;
      claude: string;
      openrouter: string;
    };
    modelGroups: {
      gpt4o: string;
      gpt4turbo: string;
    };
    openrouterModel: string;
    openrouterWebsite: string;
  };
  settings: {
    power_user: {
      spoiler_free_mode: {
        label: string;
        description: string;
      };
      never_resize_avatars: {
        label: string;
        description: string;
      };
      send_on_enter: {
        label: string;
        description: string;
        options: {
          disabled: string;
          auto: string;
          enabled: string;
        };
      };
      auto_fix_generated_markdown: {
        label: string;
        description: string;
      };
      world_import_dialog: {
        label: string;
        description: string;
      };
      confirm_message_delete: {
        label: string;
        description: string;
      };
      movingUI: {
        label: string;
        description: string;
      };
      zoomed_avatar_magnification: {
        label: string;
        description: string;
      };
      characters_per_page: {
        label: string;
        description: string;
      };
    };
    background: {
      thumbnailColumns: {
        label: string;
        description: string;
      };
      animation: {
        label: string;
        description: string;
      };
    };
  };
}
