import type { AiConfigSection } from './types';

export const aiConfigDefinition: AiConfigSection[] = [
  {
    id: 'presets',
    items: [
      {
        widget: 'preset-manager',
        id: 'api.selectedSampler',
        label: 'aiConfig.presets.sampler.label',
      },
    ],
  },
  {
    id: 'prompt-management',
    items: [
      {
        widget: 'prompt-manager-button',
        label: 'aiConfig.promptManager.label',
        description: 'aiConfig.promptManager.description',
      },
    ],
  },
  {
    id: 'common-settings',
    items: [
      {
        id: 'api.samplers.max_context',
        widget: 'slider',
        label: 'aiConfig.contextSize.label',
        min: 512,
        max: 4095, // Default for older models, will be updated from API
        step: 1,
        maxUnlockedId: 'api.samplers.max_context_unlocked',
        unlockLabel: 'aiConfig.contextSize.unlocked',
        unlockTooltip: 'aiConfig.contextSize.unlockedTooltip',
      },
      {
        id: 'api.samplers.max_tokens',
        widget: 'number-input',
        label: 'aiConfig.maxResponseLength.label',
        min: 1,
        max: 128000,
        step: 1,
      },
      { widget: 'hr' },
      {
        id: 'api.samplers.stream',
        widget: 'checkbox',
        label: 'aiConfig.streaming.label',
        description: 'aiConfig.streaming.description',
      },
      {
        id: 'api.samplers.show_thoughts',
        widget: 'checkbox',
        label: 'aiConfig.showThoughts.label',
        description: 'aiConfig.showThoughts.description',
        conditions: {
          provider: [
            'claude',
            'deepseek',
            'aimlapi',
            'openrouter',
            'custom',
            'xai',
            'makersuite',
            'vertexai',
            'pollinations',
            'moonshot',
            'mistralai',
            'fireworks',
            'cometapi',
            'electronhub',
            'azure_openai',
            'nanogpt',
            'zai',
          ],
        },
      },
      {
        id: 'api.samplers.reasoning_effort',
        widget: 'select',
        label: 'aiConfig.reasoningEffort.label',
        infoTooltip: 'aiConfig.reasoningEffort.tooltip',
        infoLink: 'https://docs.sillytavern.app/usage/prompts/reasoning/#reasoning-effort',
        conditions: {
          provider: [
            'openai',
            'custom',
            'claude',
            'xai',
            'makersuite',
            'vertexai',
            'aimlapi',
            'openrouter',
            'pollinations',
            'perplexity',
            'cometapi',
            'electronhub',
            'azure_openai',
          ],
        },
        options: [
          { value: 'auto', label: 'aiConfig.reasoningEffort.options.auto' },
          { value: 'min', label: 'aiConfig.reasoningEffort.options.minimum' },
          { value: 'low', label: 'aiConfig.reasoningEffort.options.low' },
          { value: 'medium', label: 'aiConfig.reasoningEffort.options.medium' },
          { value: 'high', label: 'aiConfig.reasoningEffort.options.high' },
          { value: 'max', label: 'aiConfig.reasoningEffort.options.maximum' },
        ],
      },
      {
        widget: 'info-display',
        description: 'aiConfig.reasoningEffort.descriptionOpenAI',
        conditions: {
          provider: ['openai', 'custom', 'xai', 'aimlapi', 'openrouter', 'perplexity', 'electronhub', 'azure_openai'],
        },
      },
      {
        widget: 'info-display',
        description: 'aiConfig.reasoningEffort.descriptionClaude',
        conditions: {
          provider: ['claude'],
        },
      },
      {
        widget: 'info-display',
        description: 'aiConfig.reasoningEffort.descriptionGoogle',
        conditions: {
          provider: ['makersuite', 'vertexai'],
        },
      },
    ],
  },
  {
    id: 'sampling-sliders-1',
    items: [
      {
        id: 'api.samplers.temperature',
        widget: 'slider',
        label: 'aiConfig.temperature.label',
        min: 0,
        max: 2,
        step: 0.01,
      },
      {
        id: 'api.samplers.frequency_penalty',
        widget: 'slider',
        label: 'aiConfig.freqPenalty.label',
        min: -2,
        max: 2,
        step: 0.01,
        conditions: {
          provider: [
            'openai',
            'aimlapi',
            'openrouter',
            'custom',
            'cohere',
            'perplexity',
            'groq',
            'mistralai',
            'electronhub',
            'nanogpt',
            'deepseek',
            'xai',
            'pollinations',
            'moonshot',
            'fireworks',
            'cometapi',
            'azure_openai',
          ],
        },
      },
      {
        id: 'api.samplers.presence_penalty',
        widget: 'slider',
        label: 'aiConfig.presPenalty.label',
        min: -2,
        max: 2,
        step: 0.01,
        conditions: {
          provider: [
            'openai',
            'aimlapi',
            'openrouter',
            'custom',
            'cohere',
            'perplexity',
            'groq',
            'mistralai',
            'electronhub',
            'nanogpt',
            'deepseek',
            'xai',
            'pollinations',
            'moonshot',
            'fireworks',
            'cometapi',
            'azure_openai',
          ],
        },
      },
      {
        id: 'api.samplers.top_k',
        widget: 'slider',
        label: 'aiConfig.topK.label',
        min: 0,
        max: 500,
        step: 1,
        conditions: {
          provider: [
            'claude',
            'aimlapi',
            'openrouter',
            'makersuite',
            'vertexai',
            'cohere',
            'perplexity',
            'electronhub',
          ],
        },
      },
      {
        id: 'api.samplers.top_p',
        widget: 'slider',
        label: 'aiConfig.topP.label',
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
  },
  {
    id: 'openrouter-sliders',
    conditions: { provider: 'openrouter' },
    items: [
      {
        id: 'api.samplers.repetition_penalty',
        widget: 'slider',
        label: 'aiConfig.repPenalty.label',
        min: 1,
        max: 2,
        step: 0.01,
      },
      {
        id: 'api.samplers.min_p',
        widget: 'slider',
        label: 'aiConfig.minP.label',
        min: 0,
        max: 1,
        step: 0.001,
      },
      {
        id: 'api.samplers.top_a',
        widget: 'slider',
        label: 'aiConfig.topA.label',
        min: 0,
        max: 1,
        step: 0.001,
      },
    ],
  },
  {
    id: 'provider-specific-settings',
    items: [
      {
        id: 'api.samplers.providers.claude.use_sysprompt',
        widget: 'checkbox',
        label: 'aiConfig.claude.useSysPrompt.label',
        description: 'aiConfig.claude.useSysPrompt.description',
        conditions: { provider: 'claude' },
      },
      {
        id: 'api.samplers.providers.claude.assistant_prefill',
        widget: 'textarea',
        label: 'aiConfig.claude.assistantPrefill.label',
        description: 'aiConfig.claude.assistantPrefill.description',
        conditions: { provider: 'claude' },
      },
      {
        id: 'api.samplers.providers.google.use_makersuite_sysprompt',
        widget: 'checkbox',
        label: 'aiConfig.google.useSysPrompt.label',
        description: 'aiConfig.google.useSysPrompt.description',
        conditions: { provider: ['makersuite', 'vertexai'] },
      },
    ],
  },
];
