import type { AiConfigSection } from './types';

export const aiConfigDefinition: AiConfigSection[] = [
  {
    id: 'presets',
    items: [
      {
        widget: 'preset-manager',
        id: 'api.selected_sampler',
        label: 'aiConfig.presets.chatCompletion.label',
      },
    ],
  },
  {
    id: 'prompt-management',
    items: [
      {
        widget: 'prompt-manager-button',
        label: 'aiConfig.promptManager.label',
        description: 'aiConfig.promptManager.description',
      },
    ],
  },
  {
    id: 'common-settings',
    conditions: { api: 'openai' },
    items: [
      {
        id: 'api.samplers.max_context',
        widget: 'slider',
        label: 'aiConfig.contextSize.label',
        min: 512,
        max: 4095, // Default for older models, will be updated from API
        step: 1,
        maxUnlockedId: 'api.samplers.max_context_unlocked',
        unlockLabel: 'aiConfig.contextSize.unlocked',
        unlockTooltip: 'aiConfig.contextSize.unlockedTooltip',
      },
      {
        id: 'api.samplers.max_tokens',
        widget: 'number-input',
        label: 'aiConfig.maxResponseLength.label',
        min: 1,
        max: 128000,
        step: 1,
      },
      { widget: 'hr' },
      {
        id: 'api.samplers.stream',
        widget: 'checkbox',
        label: 'aiConfig.streaming.label',
        description: 'aiConfig.streaming.description',
      },
      {
        id: 'api.samplers.show_thoughts',
        widget: 'checkbox',
        label: 'aiConfig.showThoughts.label',
        description: 'aiConfig.showThoughts.description',
        conditions: {
          source: [
            'claude',
            'deepseek',
            'aimlapi',
            'openrouter',
            'custom',
            'xai',
            'makersuite',
            'vertexai',
            'pollinations',
            'moonshot',
            'mistralai',
            'fireworks',
            'cometapi',
            'electronhub',
            'azure_openai',
            'nanogpt',
            'zai',
          ],
        },
      },
    ],
  },
  {
    id: 'sampling-sliders-1',
    conditions: { api: 'openai' },
    items: [
      {
        id: 'api.samplers.temperature',
        widget: 'slider',
        label: 'aiConfig.temperature.label',
        min: 0,
        max: 2,
        step: 0.01,
      },
      {
        id: 'api.samplers.frequency_penalty',
        widget: 'slider',
        label: 'aiConfig.freqPenalty.label',
        min: -2,
        max: 2,
        step: 0.01,
        conditions: {
          source: [
            'openai',
            'aimlapi',
            'openrouter',
            'custom',
            'cohere',
            'perplexity',
            'groq',
            'mistralai',
            'electronhub',
            'nanogpt',
            'deepseek',
            'xai',
            'pollinations',
            'moonshot',
            'fireworks',
            'cometapi',
            'azure_openai',
          ],
        },
      },
      {
        id: 'api.samplers.presence_penalty',
        widget: 'slider',
        label: 'aiConfig.presPenalty.label',
        min: -2,
        max: 2,
        step: 0.01,
        conditions: {
          source: [
            'openai',
            'aimlapi',
            'openrouter',
            'custom',
            'cohere',
            'perplexity',
            'groq',
            'mistralai',
            'electronhub',
            'nanogpt',
            'deepseek',
            'xai',
            'pollinations',
            'moonshot',
            'fireworks',
            'cometapi',
            'azure_openai',
          ],
        },
      },
      {
        id: 'api.samplers.top_k',
        widget: 'slider',
        label: 'aiConfig.topK.label',
        min: 0,
        max: 500,
        step: 1,
        conditions: {
          source: ['claude', 'aimlapi', 'openrouter', 'makersuite', 'vertexai', 'cohere', 'perplexity', 'electronhub'],
        },
      },
      {
        id: 'api.samplers.top_p',
        widget: 'slider',
        label: 'aiConfig.topP.label',
        min: 0,
        max: 1,
        step: 0.01,
      },
    ],
  },
  {
    id: 'openrouter-sliders',
    conditions: { source: 'openrouter' },
    items: [
      {
        id: 'api.samplers.repetition_penalty',
        widget: 'slider',
        label: 'aiConfig.repPenalty.label',
        min: 1,
        max: 2,
        step: 0.01,
      },
      {
        id: 'api.samplers.min_p',
        widget: 'slider',
        label: 'aiConfig.minP.label',
        min: 0,
        max: 1,
        step: 0.001,
      },
      {
        id: 'api.samplers.top_a',
        widget: 'slider',
        label: 'aiConfig.topA.label',
        min: 0,
        max: 1,
        step: 0.001,
      },
    ],
  },
];
